database:
  dialect: mysql
  user: root
  password:
  host:
  port:
  dbname: wordblock
  max_idle_conn: 10
  max_open_conn: 100
  debug: true
  auto_migrate: false
  ssl_mode: disable

gin:
  mode: debug
  listen: ":6666"

redis:
  network: tcp
  address:
  port: 6379
  db: 11
  password:

session:
  expires_time: 604800
  key_pairs: xxxxx-xxxx-xxxx-xxx--xxx

email:
  auth_code:
  from:
  username:

web_storage:
  token: