version: '3.1'
services:

  wordblock-backend:
    image: wordblock-backend-image
    volumes:
      - ./config.yaml:/var/config/config.yaml
      # - /etc/localtime:/etc/localtime
    ports:
      - "9999:9999"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
